package pbj.math.graph;


/**
A little utility class that reads a GraphMap and computes its n-th power.
Usage: java pbj.math.graph.Powers n <filename>
@author Peter Brinkmann
@version $Id: Powers.java,v 1.1 2009/04/27 00:41:17 brinkman Exp $
@see GraphMap
 */
public class Powers {

	/** version stamp generated by rcs */
	public static final String version="$Id: Powers.java,v 1.1 2009/04/27 00:41:17 brinkman Exp $";

	public static void main (String s[]) {
		GraphMap g=new GraphMap();
		GraphMap g2=new GraphMap();
		int i,n;

		try{
			if (s.length>1)
				g.readFromFile(s[1]);
			else
				g.readFromFile("");
		} catch(Exception e) {System.err.println(e.toString());
		return; }

		if (s.length>0)
			n=Integer.parseInt(s[0]);
		else
			n=1;

		g2.copyGraph(g);

		for (i=1;i<n;i++)
			g.compose(g2);

		System.out.println(g.toString());
	}

}
